export const E_WASTE_DATA = {
	"Information Technology and Telecommunication Equipment": [
		{ code: "ITEW1", description: "Centralized Data Processing: Mainframe", avgLife: 10 },
		{ code: "ITEW1", description: "Centralized Data Processing: Minicomputers", avgLife: 5 },
		{ code: "ITEW2", description: "Personal Computing: Personal Computers (Central Processing Unit with input and output devices)", avgLife: 6 },
		{ code: "ITEW3", description: "Personal Computing: Laptop Computers (Central Processing Unit with input and output devices)", avgLife: 5 },
		{ code: "ITEW4", description: "Personal Computing: Notebook Computers", avgLife: 5 },
		{ code: "ITEW5", description: "Personal Computing: Notepad Computers", avgLife: 5 },
		{ code: "ITEW6", description: "Printers including Cartridges", avgLife: 10 },
		{ code: "ITEW7", description: "Copying Equipment", avgLife: 8 },
		{ code: "ITEW8", description: "Electrical and Electronic Typewriters", avgLife: 5 },
		{ code: "ITEW9", description: "User Terminals and Systems", avgLife: 6 },
		{ code: "ITEW10", description: "Facsimile", avgLife: 10 },
		{ code: "ITEW11", description: "Telex", avgLife: 5 },
		{ code: "ITEW12", description: "Telephones", avgLife: 9 },
		{ code: "ITEW13", description: "Pay Telephones", avgLife: 9 },
		{ code: "ITEW14", description: "Cordless Telephones", avgLife: 9 },
		{ code: "ITEW15", description: "Cellular Telephones : Feature Phones", avgLife: 7 },
		{ code: "ITEW15", description: "Cellular Telephones : Smart phones", avgLife: 5 },
		{ code: "ITEW16", description: "Answering Systems", avgLife: 5 },
		{ code: "ITEW17", description: "Products or equipment of Transmitting sound, images or other information by Telecommunications and Bluetooth enabled devices - Smart Watch/ Fitness Band, Bluetooth Headset,Virtual Reality Camera, etc", avgLife: 3 },
		{ code: "ITEW17", description: "Products or equipment of Transmitting sound, images or other information by Telecommunications – Telecommunication Antenna", avgLife: 7 },
		{ code: "ITEW17", description: "Products or equipment of Transmitting sound, images or other information by Telecommunications – Transmitters", avgLife: 5 },
		{ code: "ITEW17", description: "Products or equipment of Transmitting sound, images or other information by Telecommunications - Wi-Fi/wireless enabled Devices", avgLife: 3 },
		{ code: "ITEW17", description: "Products or equipment of Transmitting sound, images or other information by Telecommunications – Radio/Satellite Telephone", avgLife: 7 },
		{ code: "ITEW17", description: "Walkie Talkie", avgLife: 5 },
		{ code: "ITEW18", description: "BTS (all components excluding structure of tower)", avgLife: 15 },
		{ code: "ITEW19", description: "Tablets, I-PAD", avgLife: 5 },
		{ code: "ITEW20", description: "Phablets", avgLife: 5 },
		{ code: "ITEW21", description: "Scanners", avgLife: 5 },
		{ code: "ITEW22", description: "Routers - Routers, Access Point and Controller, LAN Switches, SDWAN, ioT Gateway, etc", avgLife: 10 },
		{ code: "ITEW23", description: "GPS", avgLife: 5 },
		{ code: "ITEW24", description: "UPS -upto 2 KVA", avgLife: 7 },
		{ code: "ITEW24", description: "UPS -greater than 2 KVA", avgLife: 10 },
		{ code: "ITEW25", description: "INVERTER -upto 2 KVA", avgLife: 7 },
		{ code: "ITEW25", description: "INVERTER -greater than 2 KVA", avgLife: 10 },
		{ code: "ITEW26", description: "Modems", avgLife: 5 },
		{ code: "ITEW27", description: "ELECTRONIC DATA STORAGE DEVICES FOR FLASH DRIVE (SMALL DEVICES)", avgLife: 5 },
		{ code: "ITEW27", description: "Electronic Data Storage Devices for large drive like server", avgLife: 10 }
	],
	"Consumer Electrical and Electronics and Photovoltaic Panels": [
		{ code: "CEEW1", description: "Television sets (including sets based on (Liquid Crystal Display and Light Emitting Diode technology)", avgLife: 9 },
		{ code: "CEEW2", description: "Refrigerator", avgLife: 10 },
		{ code: "CEEW3", description: "Washing Machine", avgLife: 9 },
		{ code: "CEEW4", description: "Air-conditioners excluding Centralized Air Conditioning Plants", avgLife: 10 },
		{ code: "CEEW5", description: "Fluorescent and other Mercury containing lamps", avgLife: 2 },
		{ code: "CEEW6", description: "Screen, Electronic Photo Frames, Electronic Display Panel, Monitors", avgLife: 7 },
		{ code: "CEEW7", description: "Radio Sets", avgLife: 8 },
		{ code: "CEEW8", description: "Set Top Boxes", avgLife: 8 },
		{ code: "CEEW9", description: "Video Cameras", avgLife: 10 },
		{ code: "CEEW10", description: "Video Recorders", avgLife: 5 },
		{ code: "CEEW11", description: "Hi-Fi Recorders", avgLife: 5 },
		{ code: "CEEW12", description: "Audio Amplifiers- Speakers, Multi Media Speaker, Home Theatre, Sound Bar, Wireless Speaker etc", avgLife: 10 },
		{ code: "CEEW13", description: "Other Products or Equipment for the purpose of recording or reproducing sound or images including signals and other technologies for the distribution of sound and image by telecommunications - CCTV Camera with DVR & NVR", avgLife: 7 },
		{ code: "CEEW13", description: "Other products or equipment for the purpose of recording or reproducing sound or images including signals and other technologies for the distribution of sound and image by telecommunications – Projector", avgLife: 7 },
		{ code: "CEEW13", description: "Other products or equipment for the purpose of recording or reproducing sound or images including signals and other technologies for the distribution of sound and image by telecommunications - Digital Sound and Video Recorder and Player", avgLife: 7 },
		{ code: "CEEW13", description: "Other Products or Equipment for the purpose of recording or reproducing sound or images including signals and other technologies for the distribution of sound and image by telecommunications", avgLife: 7 },
		{ code: "CEEW13", description: "HDCOM USED FOR VIDEO CONFERENCING", avgLife: 10 },
		{ code: "CEEW14", description: "Solar Panels/Cells, Solar Photovoltaic Panels/Cells/Modules.", avgLife: 15 },
		{ code: "CEEW15", description: "Luminaires for fluorescent lamps with the exception of luminaires in households", avgLife: 2 },
		{ code: "CEEW16", description: "High intensity discharge lamps, including Pressure Sodium Lamps and Metal Halide Lamps", avgLife: 2 },
		{ code: "CEEW17", description: "Low pressure Sodium Lamps", avgLife: 2 },
		{ code: "CEEW18", description: "Other lighting or equipment for the purpose of spreading or controlling light excluding Filament Bulbs - LED Bulbs/Tubes/Consumer Luminaries & Consumer LED Drives", avgLife: 4 },
		{ code: "CEEW18", description: "Other lighting or equipment for the purpose of spreading or controlling light excluding Filament Bulbs - Professionals Luminaries & Drives", avgLife: 8 },
		{ code: "CEEW19", description: "Digital Camera", avgLife: 5 }
	],
	"Large and Small Electrical Equipment": [
		{ code: "LSEEW1", description: "Large cooling appliances", avgLife: 10 },
		{ code: "LSEEW2", description: "Freezers", avgLife: 10 },
		{ code: "LSEEW3", description: "Other large appliances used for refrigeration, conservation and storage of food", avgLife: 10 },
		{ code: "LSEEW4", description: "Clothes Dryers", avgLife: 10 },
		{ code: "LSEEW5", description: "Dish Washing Machines", avgLife: 10 },
		{ code: "LSEEW6", description: "Electric Cookers", avgLife: 7 },
		{ code: "LSEEW7", description: "Electric Stoves", avgLife: 7 },
		{ code: "LSEEW8", description: "Electric Hot Plates", avgLife: 5 },
		{ code: "LSEEW9", description: "Microwaves, Microwave Oven", avgLife: 10 },
		{ code: "LSEEW10", description: "Other large appliances used for cooking and other processing of food", avgLife: 10 },
		{ code: "LSEEW11", description: "Electric Heating Appliances", avgLife: 10 },
		{ code: "LSEEW12", description: "Electric Radiators", avgLife: 7 },
		{ code: "LSEEW13", description: "Other large appliances for heating Rooms, Beds, Seating Furniture", avgLife: 7 },
		{ code: "LSEEW14", description: "Electric Fans", avgLife: 10 },
		{ code: "LSEEW15", description: "Other Fanning, exhaust Ventilation and Conditioning Equipment", avgLife: 10 },
		{ code: "LSEEW16", description: "Vacuum Cleaners", avgLife: 10 },
		{ code: "LSEEW17", description: "Carpet Sweepers", avgLife: 10 },
		{ code: "LSEEW18", description: "Other appliances for cleaning", avgLife: 10 },
		{ code: "LSEEW19", description: "Appliances used for sewing, knitting, weaving and other processing for textiles", avgLife: 7 },
		{ code: "LSEEW20", description: "Iron and other appliances for ironing, mangling and other care of clothing - Dry Iron", avgLife: 15 },
		{ code: "LSEEW20", description: "Iron and other appliances for ironing, mangling and other care of clothing - Steam Iron/Garment Steamer", avgLife: 10 },
		{ code: "LSEEW21", description: "Grinders, Coffee Machines and equipment for opening or sealing containers or packages", avgLife: 10 },
		{ code: "LSEEW22", description: "Smoke Detector", avgLife: 10 },
		{ code: "LSEEW23", description: "Heating Regulators", avgLife: 5 },
		{ code: "LSEEW24", description: "Thermostats", avgLife: 5 },
		{ code: "LSEEW25", description: "Automatic Dispensers for hot drinks", avgLife: 7 },
		{ code: "LSEEW26", description: "Automatic Dispensers for hot or cold bottles or cans", avgLife: 7 },
		{ code: "LSEEW27", description: "Automatic Dispensers for solid products", avgLife: 10 },
		{ code: "LSEEW28", description: "Automatic Dispensers for money", avgLife: 10 },
		{ code: "LSEEW29", description: "All appliances which deliver automatically all kinds of products", avgLife: 10 },
		{ code: "LSEEW30", description: "Indoor Air Purifier", avgLife: 10 },
		{ code: "LSEEW31", description: "Hair Dryer", avgLife: 5 },
		{ code: "LSEEW32", description: "Electric Shaver", avgLife: 5 },
		{ code: "LSEEW33", description: "Electric Kettle", avgLife: 5 },
		{ code: "LSEEW34", description: "Electronic Display Panels/Board/Visual Display Unit", avgLife: 9 }
	],
	"Electric and Electronic Tools (Exception of Large Scale Stationary Industrial Tools)": [
		{ code: "EETW1", description: "Drills", avgLife: 8 },
		{ code: "EETW2", description: "Saws", avgLife: 10 },
		{ code: "EETW3", description: "Sewing Machines", avgLife: 15 },
		{ code: "EETW4", description: "Equipment for turning, milling, sanding, grinding, sawing, cutting, shearing, drilling, making holes, punching, folding, bending or similar processing of wood, metal and other materials", avgLife: 10 },
		{ code: "EETW5", description: "Tools for riveting, nailing or screwing or removing rivets, nails, screws or similar uses", avgLife: 10 },
		{ code: "EETW6", description: "Tools for welding, soldering, or similar use", avgLife: 10 },
		{ code: "EETW7", description: "Equipment for spraying, spreading, dispersing or other treatment of liquid or gaseous substance by other means", avgLife: 10 },
		{ code: "EETW8", description: "Tools for mowing or other gardening activities", avgLife: 10 }
	],
	"Toys, Leisure and Sports Equipment": [
		{ code: "TLSEW1", description: "Electrical Trains or Car Racing Sets", avgLife: 2 },
		{ code: "TLSEW2", description: "Hand-held Video Games Consoles", avgLife: 2 },
		{ code: "TLSEW3", description: "Video Games", avgLife: 2 },
		{ code: "TLSEW4", description: "Computers for biking, diving, running, rowing, etc.", avgLife: 5 },
		{ code: "TLSEW5", description: "Sports Equipment with Electric or Electronic Components", avgLife: 5 },
		{ code: "TLSEW6", description: "Coin Slot Machines", avgLife: 8 }
	],
	"Medical Devices": [
		{ code: "MDW1", description: "Radiotherapy Equipment and Accessories", avgLife: 20 },
		{ code: "MDW2", description: "Cardiology Equipment and Accessories", avgLife: 10 },
		{ code: "MDW3", description: "Dialysis Equipment and Accessories", avgLife: 10 },
		{ code: "MDW4", description: "Pulmonary Ventilators and Accessories - Diagnostic Cardiology", avgLife: 7 },
		{ code: "MDW4", description: "Pulmonary ventilators and accessories - Anaesthesia & Respiratory", avgLife: 10 },
		{ code: "MDW5", description: "Nuclear Medicine Equipment and accessories", avgLife: 20 },
		{ code: "MDW6", description: "Laboratory Equipment for in Vitro Diagnosis and Accessories", avgLife: 15 },
		{ code: "MDW7", description: "Analysers and Accessories", avgLife: 10 },
		{ code: "MDW8", description: "Magnetic Resonance Imaging (MRI), Positron Emission Tomography (PET) Scanner, Computed Tomography Scanner, & Ultrasound Equipment along with accessories - MRI", avgLife: 15 },
		{ code: "MDW8", description: "Magnetic Resonance Imaging (MRI), Positron Emission Tomography (PET) Scanner, Computed Tomography Scanner, & Ultrasound Equipment along with accessories - PET CT/PET", avgLife: 20 },
		{ code: "MDW8", description: "Magnetic Resonance Imaging (MRI), Positron Emission Tomography (PET) Scanner, Computed Tomography Scanner, & Ultrasound Equipment along with accessories - SPECT CT/ SPECT", avgLife: 20 },
		{ code: "MDW8", description: "Magnetic Resonance Imaging (MRI), Positron Emission Tomography (PET) Scanner, Computed Tomography Scanner, & Ultrasound Equipment along with accessories - CT", avgLife: 15 },
		{ code: "MDW8", description: "Magnetic Resonance Imaging (MRI), Positron Emission Tomography (PET) Scanner, Computed Tomography Scanner, & Ultrasound Equipment along with accessories and US, probe etc", avgLife: 10 },
		{ code: "MDW8", description: "Magnetic Resonance Imaging (MRI), Positron Emission Tomography (PET) Scanner, Computed Tomography Scanner, & Ultrasound Equipment along with accessories - Computed Tomography", avgLife: 20 },
		{ code: "MDW8", description: "Magnetic Resonance Imaging (MRI), Positron Emission Tomography (PET) Scanner, Computed Tomography Scanner, & Ultrasound Equipment along with accessories - Ultrasound Diagnostic Imaging", avgLife: 10 },
		{ code: "MDW9", description: "Fertilization Tests Equipment and Accessories", avgLife: 10 },
		{ code: "MDW10", description: "Other Electric Appliances/Equipment/Kits used for preventing, screening, detecting, monitoring, evaluating, reviewing, examining, investigating, probing, treating illness sickness, disease, disorder, affliction, infection, injury, trauma, abuse or disability including the Mobiles, Tablets or any other device with the features having the potential of sex selection and their accessories- Maternal & Infant Care Products", avgLife: 7 },
		{ code: "MDW10", description: "Other Electric Appliances/Equipment/Kits used for preventing, screening, detecting, monitoring, evaluating, reviewing, examining, investigating, probing, treating illness sickness, disease, disorder, affliction, infection, injury, trauma, abuse or disability including the Mobiles, Tablets or any other device with the features having the potential of sex selection and their accessories- C-Arm", avgLife: 12 },
		{ code: "MDW10", description: "Other Electric appliances/equipment/kits used for preventing, screening, detecting, monitoring, evaluating, reviewing, examining, investigating, probing, treating illness sickness, disease, disorder, affliction, infection, injury, trauma, abuse or disability including the Mobiles, Tablets or any other device with the features having the potential of sex selection and their accessories - Monitoring Solution Products/High End", avgLife: 15 },
		{ code: "MDW10", description: "Other electric appliances/equipment/kits used for preventing, screening, detecting, monitoring, evaluating, reviewing, examining, investigating, probing, treating illness sickness, disease, disorder, affliction, infection, injury, trauma, abuse or disability including the Mobiles, Tablets or any other device with the features having the potential of sex selection and their accessories - X-Ray and Fluoroscopy", avgLife: 12 },
		{ code: "MDW10", description: "Other electric appliances/equipment/kits used for preventing, screening, detecting, monitoring, evaluating, reviewing, examining, investigating, probing, treating illness sickness, disease, disorder, affliction, infection, injury, trauma, abuse or disability including the Mobiles, Tablets or any other device with the features having the potential of sex selection and their accessories - Mammography Devices", avgLife: 12 },
		{ code: "MDW10", description: "Other Electric Appliances/Equipment/Kits used for preventing, screening, detecting, monitoring, evaluating, reviewing, examining, investigating, probing, treating illness sickness, disease, disorder, affliction, infection, injury, trauma, abuse or disability including the Mobiles, Tablets or any other device with the features having the potential of sex selection and their accessories", avgLife: 7 }
	],
	"Laboratory Instruments": [
		{ code: "LIW1", description: "Gas Analyser", avgLife: 8 },
		{ code: "LIW2", description: "Equipment having Electrical and Electronic Components", avgLife: 8 }
	]
};
